### ISSUE TITLE
Clean up the `extern` directory

### ISSUE THREAD

**Issue by Kenix3** [Kenix3/libultraship#509]
We should not be relying on any external repositories committed into LUS.

Supercedes https://github.com/Kenix3/libultraship/issues/500

- [x] [dr_libs](https://github.com/mackron/dr_libs) ~(Fetch a commit from SHA)~ remove until we have a need for it in a `Ship::` resource
- [x] [stb](https://github.com/nothings/stb) (Fetch from a commit SHA) (blocked by https://github.com/Kenix3/libultraship/issues/485)
- [x] [thread-pool](https://github.com/bshoshany/thread-pool) (Fetch from tags)
- [x] [StormLib](https://github.com/ladislav-zezula/StormLib) (We 100% used to have changes, but I don't think we do anymore. Double check before converting.) (Might need to just fetch from tag) (blocked by: https://github.com/Kenix3/libultraship/issues/442)
- [x] [libgfxd](https://github.com/glankk/libgfxd) (Need to fetch from commit SHA) (may conflict with https://github.com/Kenix3/libultraship/issues/521)
- [x] [imgui](https://github.com/ocornut/imgui) (There are not packages for the docking branch, might need to fetch) (There may be some changes, but it is believed they are Switch specific) (blocked by https://github.com/Kenix3/libultraship/issues/485)
- [x] [nlohmann-json](https://github.com/nlohmann/json) (Has all packages we need)
- [x] [spdlog](https://github.com/gabime/spdlog) (Has all packages we need)
- [x] [tinyxml2](https://github.com/leethomason/tinyxml2) ~(Fetch from tags)~ looking into package manager
- [x] StrHash64 (Don't know what repo we took this from, if any. Can just absorb the code)
- [x] ZAPDUtils (https://github.com/Kenix3/libultraship/issues/484)
- [x] metal-cpp (We don't know where this came from, but worst case it could be absorbed into the renderer)

**Comment by briaguya0** [comment]
see https://github.com/Kenix3/libultraship/pull/374 for imgui stuff - i see 2 options for paths forward here

either

* fork imgui and apply our changes from extern there
* pull from sha on fork until https://github.com/Kenix3/libultraship/issues/485
* switch to pulling from upstream sha

or

* keep it in the extern dir until https://github.com/Kenix3/libultraship/issues/485
* switch to pulling from upstream sha

**Comment by Archez** [comment]
`metal-cpp` is made by Apple and provided as a download zip from their domain, different versions are listed in their landing page https://developer.apple.com/metal/cpp/

There are some clones of these files on github by various users. I don't know if we want to trust one of these github clones, or pull directly from Apple as a .zip/extract.

It looks like we use the "single header" alternative, which requires executing a python script provided in the .zip to generate the resulting header file.
